// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibvmcjzhnkkgizagjmuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlidm1janpobmtrZ2l6YWdqbXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTA5MjgsImV4cCI6MjA3MDU4NjkyOH0.yVW6S0WIkY6hRllQ-uYTUR1cuHnGed1fGsfczyKtJrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});